[build]
builder = "NIXPACKS"
buildCommand = ""
watchPaths = []

[deploy]
rootDirectory = "backend"
startCommand = "python app.py"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
numReplicas = 1
